name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main  # sempre que atualizar a branch main
  workflow_dispatch: # também permite rodar manualmente

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependências
        run: |
          pip install mkdocs mkdocs-material

      - name: Build e Deploy
        run: mkdocs gh-deploy --force
